version: '2'

services:
  mysql-service:
    image: mysql-img
    container_name: mysql-svc
    build: ./mysql-setup
    ports:
      - 3306:3306
  keymanager-service:
    image: keymanager-img
    container_name: keymanager-svc
    build:
      context: ./keymanager-setup
    depends_on: 
      - mysql-service
    ports:
      - 9444:9444
      - 9764:9764
  apim-service:
    image: apim-img
    container_name: apim-svc
    build:
      context: ./apim-setup
    depends_on: 
      - mysql-service
      - keymanager-service
    ports:
      - 9443:9443
      - 9763:9763
      - 8280:8280
      - 8243:8243