version: '2'

services:
  mysql-service:
    image: mysql-img
    container_name: mysql-svc
    build: ./mysql-setup
    ports:
      - 3306:3306

  apim-sso-service:
    image: apim-sso-img
    container_name: apim-sso-svc
    build:
      context: ./apim-sso-setup
    depends_on: 
      - mysql-service
    ports:
      - 9544:9544
      - 9864:9864
      - 9543:9543
      - 9863:9863
      - 8380:8380
      - 8343:8343